<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>Ghostwriter.App</RootNamespace>
    <AssemblyName>Ghostwriter</AssemblyName>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <TieredPGO>true</TieredPGO>
    <TieredCompilation>true</TieredCompilation>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ghostwriter.Core\Ghostwriter.Core.csproj" />
    <ProjectReference Include="..\Ghostwriter.Platform\Ghostwriter.Platform.csproj" />
  </ItemGroup>

</Project>
